### ISSUE TITLE
Support 16bit float for buffer

### ISSUE THREAD

**Issue by jaebaek** [google/amber#546] opened 2019-06-11 16:43 UTC
When I wrote a test script for DXC, I realized we need 16 bit float for data type of a buffer.
See [dx-graphics-hlsl-scalar](https://docs.microsoft.com/ko-kr/windows/desktop/direct3dhlsl/dx-graphics-hlsl-scalar).

Probably we can name the type as `half`.

**Comment by dj2** [comment] 2019-07-22 13:16
This is a dupe of #485

**Closed by dj2** 2019-07-22 13:16 UTC
Labels: duplicate
