### ISSUE TITLE
Vulkan backend does not build under Windows with Visual Studio 2017

### ISSUE THREAD

**Issue by afd** [google/amber#318] opened 2019-02-22 13:53 UTC
I find that the Vulkan back-end fails to build under Windows with the error below.

It looks like the CI is not building this for Windows.

The issue can be trivially fixed via some additions of #include <cassert>.  It would be great to have the Vulkan back-end building in the CI, though.

[420/440] Building CXX object src\vulkan\CMakeFiles\libamberenginevulkan.dir\image.cc.obj
FAILED: src/vulkan/CMakeFiles/libamberenginevulkan.dir/image.cc.obj
C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DAMBER_CTS_VULKAN_HEADER=0 -DAMBER_ENABLE_SHADERC=1 -DAMBER_ENABLE_SPIRV_TOOLS=1 -DAMBER_ENGINE_DAWN=0 -DAMBER_ENGINE_VULKAN=1 -I..\include -I..\ -I..\third_party\spirv-tools\include -IC:\VulkanSDK\1.1.97.0\Include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MT /bigobj /EHsc /W3 /WX /wd4068 /wd4514 /wd4571 /wd4625 /wd4626 /wd4710 /wd4774 /wd4820 /wd5026 /wd5027 /MT /O2 /Ob2 /DNDEBUG   /EHs /showIncludes /Fosrc\vulkan\CMakeFiles\libamberenginevulkan.dir\image.cc.obj /Fdsrc\vulkan\CMakeFiles\libamberenginevulkan.dir\libamberenginevulkan.pdb /FS -c ..\src\vulkan\image.cc
..\src\vulkan\image.cc(247): error C3861: 'assert': identifier not found
[425/440] Building CXX object src\CMakeFiles\amber_unittests.dir\vkscript\command_parser_test.cc.obj
ninja: build stopped: subcommand failed.

**Comment by dj2** [comment] 2019-03-04 15:12
Is this fixed with #320?

**Comment by paulthomson** [comment] 2019-03-04 16:27
Yes I believe so.

**Comment by dj2** [comment] 2019-03-04 16:33
Ok, closing this for now. Please re-open if the issue is still occurring.

**Closed by dj2** 2019-03-04 16:33 UTC
